declare interface RbxthumbIndex {
	Asset: "150x150" | "294x144" | "420x420" | "480x270" | "768x432";
	AutoGeneratedAsset: "150x150" | "420x420";
	Avatar: "48x48" | "60x60" | "100x100" | "150x150" | "180x180" | "352x352" | "420x420" | "720x720";
	AvatarBust: "48x48" | "50x50" | "60x60" | "75x75" | "100x100" | "150x150" | "180x180" | "352x352" | "420x420";
	AvatarHeadShot: "48x48" | "60x60" | "100x100" | "150x150" | "180x180" | "352x352" | "420x420";
	BadgeIcon: "150x150";
	BundleThumbnail: "150x150" | "420x420";
	DeveloperProduct: "150x150" | "420x420";
	FontFamily: "1200x80";
	GameIcon: "50x50" | "128x128" | "150x150" | "256x256" | "512x512";
	GamePass: "150x150";
	GameThumbnail: "256x144" | "384x216" | "480x270" | "576x324" | "768x432";
	GroupIcon: "150x150" | "420x420";
	// Look: ""; Look is not yet a supported type for rbxthumb. (nov 04th, 2023)
	Outfit: "150x150" | "420x420";
}

declare function createRbxthumb<T extends keyof RbxthumbIndex>(
	thumbnailType: T,
	thumbnailId: number,
	thumbnailSize: RbxthumbIndex[T],
	isCircular?: boolean,
): string;

export = createRbxthumb;
